all:
	g++ -std=c++11 -g -Wall -o dt main.cpp DataSet.h DataSet.cpp Example.h Example.cpp DecisionTree.h DecisionTree.cpp DecisionTreeLearner.h DecisionTreeLearner.cpp StringUtils.h

clean:
  rm -f *.o
  rm -f *~ *# .#*